# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentName', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('recordID', models.IntegerField()),
                ('crewID', models.IntegerField()),
                ('supervisorName', models.CharField(max_length=200)),
                ('dateOnSite', models.CharField(max_length=200)),
            ],
        ),
    ]
