# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='building_type',
            field=models.CharField(choices=[('I', 'Industrial'), ('C', 'Commercial'), ('R', 'Residential')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='gps_coordinates',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='moniker',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='nearest_cross_street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='number_of_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='property_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
