# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedb', '0002_auto_20160503_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(default='C:\\Users\\jannainm\\workspace\\GITSdbes.jpg', upload_to=b''),
        ),
    ]
