# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedb', '0003_incident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='image',
            field=models.ImageField(default='C:\\Users\\jannainm\\workspace\\GITSdbdefault.jpg', upload_to=b''),
        ),
    ]
